CREATE DATABASE IF NOT EXISTS burgers_db
USE burgers_db;

CREATE TABLE IF NOT NOT EXISTS burgers (

id INT (10) AUTO_INCREMENT NOT NULL,
burger_name VARCHAR(255) NOT NULL,
devoured BOOLEAN DEFAULT false,
date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(id)
);

SET time_zone='+00:00';



