CREATE DATABASE IF NOT EXISTS burgers_db
#USE burgers_db;

CREATE TABLE IF NOT EXISTS burgers (

id INT (10) AUTO_INCREMENT NOT NULL,
burger_name VARCHAR(255) NOT NULL,
devoured BOOLEAN DEFAULT false,
date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY(id)
);





