CREATE DATABASE IF NOT EXISTS burgers_db
USE burgers_db;

CREATE TABLE IF NOT NOT EXISTS burgers (

item INT (10) AUTO_INCREMENT NOT NULL,
burger_name VARCHAR(255) NOT NULL,
devoured VARCHAR(255) NOT NULL,
date DECIMAL (10, 2) NOT NULL,
stock_quantity INT(30) NOT NULL, 
PRIMARY KEY(item_id)
